### ISSUE TITLE
No such element error

### ISSUE THREAD

**Issue by edgemund** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#1]
Thanks for your codes. I find it simple and straightforward to use.

I tried to make some adjustments to use it in a project but I faced this error:

1. Message: no such element: Unable to locate element: {"method":"xpath","selector":"//label[@for="filters_detail_checkbox_trating__5"]"}

2. Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class="nav next taLnk ui_button primary"]"}

I have attached a copy of my scripts to this.

I will appreciate your help.

[Louvre Museum.zip](https://github.com/giuseppegambino/Scraping-TripAdvisor-with-Python-2019/files/4276251/Louvre.Museum.zip)

**Comment by giuseppegambino** [comment]
Hi @edgemund, I found the bug! 
I try to explain it clearly, in a nutshell the structure of the TripAdvisor site changes often, at least twice a year. I suppose it's a move to make scraping scripts like this obsolete.

The solution when you find such errors is to use the "inspect" mode of your browser, to see if the name of the label or class of a button has changed, and in that case update the code!

For this time you just need to replace the string "nav next taLnk ui_button primary" with the new string "nav next ui_button primary  cx_brand_refresh_phase2". 

In this way it works for me again, unfortunately I don't see the other bug for selecting the rating. 

However, I advise you never to change the size of the web page that opens automatically, because the structure of the page and therefore the various buttons, links, etc. also change.

I hope I have been useful to you, bye
