### ISSUE TITLE
ElementClickInterceptedException

### ISSUE THREAD

**Issue by Didiergrimaldi** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#10]
hello Guiseppe,
i am using Python 3 and i have including the encoding="utf-8".
The code works better but after 60 changes of page, i have another error message:

"ElementClickInterceptedException: Message: element click intercepted: Element <span class="taLnk ulBlueLinks" onclick="widgetEvCall('handlers.clickExpand',event,this);">...</span> is not clickable at point (408, 564). Other element would receive the click: <p class="partial_entry" lang="es-x-mtfrom-en">...</p>
  (Session info: chrome=87.0.4280.88)"

any idea?
thks
Didier

**Comment by giuseppegambino** [comment]
Hello @Didiergrimaldi ,
what website are you scraping? So, I can do some targeted tests.

Maybe Tripadvisor randomly sends banners/popup that make the buttons not clickable.

In any case try this **workaround**:
You can scrape a tripadvisor page also from a specific page, for example if you are doing web scraping of the Colosseum, you can also start from the 60th page, passing the correct url link: [https://www.tripadvisor.com/Attraction_Review-g187791-d192285-Reviews-or300-Colosseum-Rome_Lazio.html](url)
In this case we have **-or300-** because the page has 5 reviews per page, so 300/5 = 60th page.

Hoping it can help you,
Giuseppe.

**Comment by Didiergrimaldi** [comment]
hello
i was scrapping a favourite restaurant: 
https://www.tripadvisor.es/Restaurant_Review-g60827-d457172-Reviews-Grimaldi_s_Pizzeria-Brooklyn_New_York.html

Please let me know!
grazie
Didier

**Comment by giuseppegambino** [comment]
i updated the code a while ago, now it should go
